name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: create-release
        with:
          result-encoding: string
          retries: 3
          script: |
            // Use GitHub REST API v3 to create a release
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref_name,
              name: context.ref_name,
              generate_release_notes: true,
            })